# https://kind.sigs.k8s.io/docs/user/using-wsl2/
# kind create cluster --config=kind-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Fix Image Pull - https://github.com/kubernetes-sigs/kind/issues/1010
  extraMounts:
   - hostPath: /mnt/c/ca-certs/ZscalerRootCertificate-2048-SHA256.crt
     containerPath: /usr/share/ca-certificates/corporate.crt
  # Ingress
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        listenAddress: 127.0.0.1
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        listenAddress: 127.0.0.1
        protocol: TCP
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=dummy"
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=dummy"
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "topology.kubernetes.io/zone=dummy"

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."metam-docker-hosted.forge.avaya.com".tls]
      insecure_skip_verify = true

    [plugins."io.containerd.grpc.v1.cri".registry.configs."flex-docker-hosted.forge.avaya.com".tls]
      insecure_skip_verify = true
