apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
  - name: simple-pod
    image: metam-docker-hosted.forge.avaya.com/cc-init-commands:0.2.50
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
  imagePullSecrets:
  - name: regcred